# Generated by Django 5.2.6 on 2025-09-21 15:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="station",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "name",
                    models.CharField(max_length=100, verbose_name="Название станции"),
                ),
                (
                    "line",
                    models.CharField(max_length=100, verbose_name="Название линии"),
                ),
                (
                    "coordinates",
                    models.CharField(
                        blank=True,
                        max_length=200,
                        null=True,
                        verbose_name="Координаты станции",
                    ),
                ),
            ],
            options={
                "verbose_name": "Станция метро",
                "verbose_name_plural": "Станции метро",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("name", "line"), name="unique_station_per_line"
                    )
                ],
            },
        ),
        migrations.CreateModel(
            name="escalator",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                ("number", models.IntegerField(verbose_name="Номер эскалатора")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working", "Работает"),
                            ("not_working", "Не работает"),
                            ("maintenance", "В обслуживании"),
                        ],
                        default="working",
                        max_length=25,
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stations.station",
                        verbose_name="Станция",
                    ),
                ),
            ],
            options={
                "verbose_name": "Эскалатор",
                "verbose_name_plural": "Эскалаторы",
                "constraints": [
                    models.UniqueConstraint(
                        fields=("station", "number"),
                        name="unique_escalator_per_station",
                    )
                ],
            },
        ),
    ]
