# Generated by Django 5.1.5 on 2025-09-21 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Station',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название станции')),
                ('line', models.CharField(max_length=100, verbose_name='Название линии')),
                ('coordinates', models.CharField(blank=True, max_length=200, null=True, verbose_name='Координаты станции')),
            ],
            options={
                'verbose_name': 'Станция метро',
                'verbose_name_plural': 'Станции метро',
                'constraints': [models.UniqueConstraint(fields=('name', 'line'), name='unique_station_per_line')],
            },
        ),
        migrations.CreateModel(
            name='Escalator',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('number', models.IntegerField(verbose_name='Номер эскалатора')),
                ('status', models.CharField(choices=[('working', 'Работает'), ('notWorking', 'Не работает'), ('mainTenance', 'В обслуживании')], default='working', max_length=25)),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Эскалатор',
                'verbose_name_plural': 'Эскалаторы',
            },
        ),
        migrations.CreateModel(
            name='Camera',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('working', 'Работает'), ('notWorking', 'Не работает'), ('mainTenance', 'В обслуживании')], default='working', max_length=25)),
                ('installed_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата установки')),
                ('description', models.TextField(null=True, verbose_name='Описание камеры')),
                ('station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cameras', to='stations.station', verbose_name='Станция')),
            ],
            options={
                'verbose_name': 'Камера',
                'verbose_name_plural': 'Камеры',
            },
        ),
        migrations.CreateModel(
            name='CameraEscalator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('camera', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.camera')),
                ('escalator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.escalator')),
            ],
            options={
                'verbose_name': 'Связь камеры и эскалатора',
                'verbose_name_plural': 'Связи камер и эскалаторов',
                'constraints': [models.UniqueConstraint(fields=('camera', 'escalator'), name='unique_camera_escalator_pair')],
            },
        ),
        migrations.AddConstraint(
            model_name='escalator',
            constraint=models.UniqueConstraint(fields=('station', 'number'), name='unique_escalator_per_station'),
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_camera_id'),
        ),
    ]
