# Generated by Django 5.2.6 on 2025-09-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('active', 'активна'), ('inactive', 'неактивна'), ('in_maintenance', 'в обслуживании')], default='active', max_length=25),
        ),
        migrations.AlterField(
            model_name='escalator',
            name='status',
            field=models.CharField(choices=[('working', 'работает'), ('not_working', 'не работает'), ('under_maintenance', 'обслуживается')], default='working', max_length=25),
        ),
    ]
