# Generated by Django 5.2.6 on 2025-09-21 15:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Camera",
            fields=[
                ("id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("working", "Работает"),
                            ("not_working", "Не работает"),
                            ("maintenance", "В обслуживании"),
                        ],
                        default="working",
                        max_length=25,
                    ),
                ),
                (
                    "installed_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата установки"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="CameraEscalator",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "camera",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stations.camera",
                    ),
                ),
                (
                    "escalator",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stations.escalator",
                    ),
                ),
                (
                    "station",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="stations.station",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="camera",
            name="escalators",
            field=models.ManyToManyField(
                related_name="cameras",
                through="stations.CameraEscalator",
                to="stations.escalator",
                verbose_name="Эскалаторы",
            ),
        ),
        migrations.AddConstraint(
            model_name="cameraescalator",
            constraint=models.UniqueConstraint(
                fields=("camera", "station"), name="unique_station_per_camera"
            ),
        ),
        migrations.AddConstraint(
            model_name="cameraescalator",
            constraint=models.UniqueConstraint(
                fields=("camera", "escalator"), name="unique_camera_escalator_pair"
            ),
        ),
    ]
