# Generated by Django 5.2.6 on 2025-09-21 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0002_camera_cameraescalator_camera_escalators_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="camera",
            name="description",
            field=models.TextField(null=True, verbose_name="Описание камеры"),
        ),
    ]
