# Generated by Django 5.2.6 on 2025-09-23 07:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0002_alter_camera_status_alter_escalator_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="escalator",
            name="station",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="escalators",
                to="stations.station",
                verbose_name="Станция",
            ),
        ),
    ]
