# Generated by Django 5.1.5 on 2025-09-21 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0003_camera_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='camera',
            name='status',
            field=models.CharField(choices=[('working', 'Работает'), ('notWorking', 'Не работает'), ('mainTenance', 'В обслуживании')], default='working', max_length=25),
        ),
        migrations.AlterField(
            model_name='escalator',
            name='status',
            field=models.CharField(choices=[('working', 'Работает'), ('notWorking', 'Не работает'), ('mainTenance', 'В обслуживании')], default='working', max_length=25),
        ),
    ]
