# Generated by Django 5.2.6 on 2025-09-23 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stations", "0003_alter_escalator_station"),
    ]

    operations = [
        migrations.AddField(
            model_name="station",
            name="key_for_front",
            field=models.CharField(max_length=100, null=True, verbose_name="Ключ"),
        ),
    ]
