# Generated by Django 5.1.5 on 2025-09-21 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stations', '0004_alter_camera_status_alter_escalator_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='camera',
            options={'verbose_name': 'Камера', 'verbose_name_plural': 'Камеры'},
        ),
        migrations.AlterModelOptions(
            name='cameraescalator',
            options={'verbose_name': 'Связь камеры и эскалатора', 'verbose_name_plural': 'Связи камер и эскалаторов'},
        ),
        migrations.RemoveConstraint(
            model_name='cameraescalator',
            name='unique_station_per_camera',
        ),
        migrations.AddConstraint(
            model_name='camera',
            constraint=models.UniqueConstraint(fields=('id',), name='unique_camera_id'),
        ),
    ]
