# Generated by Django 5.1.5 on 2025-09-21 18:24

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('stations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IncidentType',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
            options={
                'verbose_name': 'Тип инцидента',
                'verbose_name_plural': 'Типы инцидентов',
            },
        ),
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('confidence', models.FloatField(validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(1)])),
                ('status', models.CharField(choices=[('Open', 'Открыто'), ('Closed', 'Закрыт'), ('inprogress', 'В работе')], default='Open', max_length=25)),
                ('notes', models.TextField()),
                ('escalator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='stations.escalator')),
                ('incident_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='incidents.incidenttype')),
            ],
            options={
                'verbose_name': 'Инцидент',
                'verbose_name_plural': 'Инциденты',
            },
        ),
    ]
