# Generated by Django 5.2.6 on 2025-09-22 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='incident',
            name='screenshot',
            field=models.ImageField(default=0, upload_to='incident_screenshots/'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='incident',
            name='status',
            field=models.CharField(choices=[('new', 'новый'), ('in_progress', 'в обработке'), ('closed', 'закрыт')], default='new', max_length=25),
        ),
    ]
