# Generated by Django 5.2.6 on 2025-09-22 17:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('incidents', '0002_incident_screenshot_alter_incident_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='incident',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, db_index=True),
        ),
        migrations.AlterField(
            model_name='incident',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='incidenttype',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
